### ISSUE TITLE
无法运行，network.py中报错; 

### ISSUE THREAD

**Issue by InhabitancyCocoon** [Galaxy922/2023-CVPR-GCFAggMVC-main#1]
def GCFAgg(self, xs)中，调用self.TransformerEncoderlayer(input)，返回值应该只有一个

commonz, S = self.TransformerEncoderLayer(commonz)

too many values to unpack

**Comment by lywinaaa** [comment]
> 

Hi，I'm also having the same issue，did you solve this problem.

**Comment by InhabitancyCocoon** [comment]
> > 
> 
> Hi，I'm also having the same issue，did you solve this problem.

no， I quit.

**Comment by zhangyuanyang21** [comment]
This problem will be resolved soon.

**Comment by lywinaaa** [comment]
> This problem will be resolved soon.

how to do it

**Comment by lywinaaa** [comment]
> 这个问题很快就会得到解决。

Looking forward to your reply

**Comment by Galaxy922** [comment]
If you can't obtain S you can refer Obtain-S.docx --already updated

**Comment by 775598508** [comment]
参考Obtain-S.docx更改完之后，可以epoch，但是epoch之后依然会出现too many values to unpack (expected 2)的问题，导致无法生成pth文件，怎样解决呢?感谢解答

**Comment by zyxforever** [comment]
为什么不重写一下那个类呢？
