### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by JuneCly** [Galaxy922/2023-CVPR-GCFAggMVC-main#8]

**Comment by Galaxy922** [comment]
你好！由于我们进行的是聚类任务，聚类是无监督学习的，所以不需要分成训练集和测试集，而是直接对所有数据进行训练，学习到伪标签后再和真实标签进行比较的。如果您发现我们的工作，对您研究的工作有用，请引用一下我们的论文，谢谢！

@InProceedings{Yan_2023_CVPR,
    author    = {Yan, Weiqing and Zhang, Yuanyang and Lv, Chenlei and Tang,
Chang and Yue, Guanghui and Liao, Liang and Lin, Weisi},
    title     = {GCFAgg: Global and Cross-View Feature Aggregation for
Multi-View Clustering},
    booktitle = {Proceedings of the IEEE/CVF Conference on Computer Vision
and Pattern Recognition (CVPR)},
    month     = {June},
    year      = {2023},
    pages     = {19863-19872}
}

**Comment by JuneCly** [comment]
好的，非常感谢您的解答！
