### ISSUE TITLE
CCV数据集

### ISSUE THREAD

**Issue by JuneCly** [Galaxy922/2023-CVPR-GCFAggMVC-main#9]
作者您好，我想要复现一下CCV数据集上的效果，但在给出的网盘文件中没有找到CCV命名的数据集，请问可以提供一个下载链接吗？非常感谢~

**Comment by Galaxy922** [comment]
https://pan.baidu.com/s/1XNWW8UqTcPMkw9NpiKqvOQ#list/path=%2F

密码: data

**Comment by JuneCly** [comment]
非常感谢解答，但是这个文件夹里好像还是没有CCV.mat文件，请问这个MFCC.npy是CCV数据集吗？


***@***.***
 
发件人： Galaxy922
发送时间： 2024-06-03 10:58
收件人： Galaxy922/GCFAggMVC
抄送： JuneCly; Author
主题： Re: [Galaxy922/GCFAggMVC] CCV数据集 (Issue #9)
https://pan.baidu.com/s/1XNWW8UqTcPMkw9NpiKqvOQ#list/path=%2F 

密码: data

**Comment by Galaxy922** [comment]
CCV.mat
<https://drive.google.com/file/d/1oT297iniA77r2INCiOYP-RBt8oPd_FEO/view?usp=drive_web>
